apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - curl-pod.yaml
  - ../../../base/grafana/grafana-operator
  - ../../../base/local-path-provisioner

patches:
  # - path: base/cert-manager/patches.yaml
