apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik  # Название чарта
      version: "2025.2.3" # Версия чарта (опционально)
      sourceRef:
        kind: HelmRepository
        name: authentik-repo
        namespace: flux-system
      interval: 1m
  values: |
    authentik:
        log_level: trace
        secret_key: "njbtxJukFsqTut66mjd0ha88iufqVLzuyyaq1CK1E4p5cRi0i0nk0Q4rlyUDggHhjKB1e59Cw30d6coy"
        # This sends anonymous usage-data, stack traces on errors and
        # performance data to sentry.io, and is fully opt-in
        error_reporting:
            enabled: false
        postgresql:
            password: "XXsZZp8PEuuyvMgohcYQFggsdMkK128RKzQSGjgcYxw9OdsHH"
    server:
        ingress:
            # Specify kubernetes ingress controller class name
            ingressClassName: nginx 
            enabled: true
            hosts:
               - authentik.xal.su
            tls:
              - secretName: wildcard-xal-su-tls-secret
                hosts:
                  - authentik.xal.su
    postgresql:
        enabled: true
        auth:
            password: "yYyYCeNsZZp8PEuuyvMgohcYQFggsdMkK8RKzQSGjgcYxw9OdskcYyYy"
    redis:
        enabled: true
