apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector
  namespace: vector
spec:
  interval: 5m
  chart:
    spec:
      chart: vector  # Название чарта
      version: "0.42.1" # Версия чарта (опционально)
      sourceRef:
        kind: HelmRepository
        name: vector-repo
        namespace: flux-system
      interval: 1m
  values:
    # Основные настройки
    role: Agent
    service:
      enabled: true
    
    # Сетевые настройки
    # hostNetwork: true
    podHostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    
    # Обход taints control-plane
    tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    
    # Запуск только на control-plane нодах
    nodeSelector:
      node-role.kubernetes.io/control-plane: ""
    
    # Конфигурация Vector
    customConfig:
      sources:
        # Kube Controller Manager
        kube_controller_manager:
          type: prometheus_scrape
          endpoints: ["https://127.0.0.1:10257/metrics"]
          auth:
            strategy: "bearer"
            token: "/var/run/secrets/kubernetes.io/serviceaccount/token"
          # bearer_token_file: "/var/run/secrets/kubernetes.io/serviceaccount/token"
          scrape_interval_secs: 15
          tls:
            verify_certificate: false
        # Kube Scheduler (добавлен)
        kube_scheduler:
          type: prometheus_scrape
          endpoints: ["https://127.0.0.1:10259/metrics"]
          bearer_token: "/var/run/secrets/kubernetes.io/serviceaccount/token"          
          scrape_interval_secs: 15
          tls:
            verify_certificate: false
        # ETCD
        kube_etcd:
          type: prometheus_scrape
          endpoints: ["http://127.0.0.1:2381/metrics"]
          scrape_interval_secs: 15
      # # Отправка метрик в Викторию
      # sinks:
        # victoria_metrics:
        #   type: prometheus_remote_write
        #   inputs: ["kube_etcd"] #["kube_controller_manager", "kube_scheduler", "kube_etcd"]
        #   endpoint: "http://vmsingle-victoria-metrics-vm.vm.svc.cluster.local:8429/api/v1/write"
        #   healthcheck:
        #     enabled: true

      # Трансляция метрик на сервисе пода ( curl http://vector.vector.svc.cluster.local:9598/metrics )
      sinks:
        etcd_prometheus_exporter:
          type: prometheus_exporter
          inputs: ["kube_etcd"]
          address: "0.0.0.0:9598"

        cm_prometheus_exporter:
          type: prometheus_exporter
          inputs: ["kube_controller_manager"]
          address: "0.0.0.0:9597"

        scheduler_prometheus_exporter:
          type: prometheus_exporter
          inputs: ["kube_scheduler"]
          address: "0.0.0.0:9599"
