apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector
  namespace: vector
spec:
  interval: 5m
  chart:
    spec:
      chart: vector  # Название чарта
      version: "0.42.1" # Версия чарта (опционально)
      sourceRef:
        kind: HelmRepository
        name: vector-repo
        namespace: flux-system
      interval: 1m
  values:
    # Основные настройки
    role: Agent
    service:
      enabled: true
    
    # Сетевые настройки
    # hostNetwork: true
    podHostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    
    # Обход taints control-plane
    tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    
    # Запуск только на control-plane нодах
    # nodeSelector:
    #   node-role.kubernetes.io/control-plane: ""
    
    # Конфигурация Vector
    customConfig:

      data_dir: /vector-data-dir
      api:
        enabled: true
        address: 127.0.0.1:8686
        playground: false

      sources:
        file_messages:
          type: file
          include:
            - /var/log/messages
        kubernetes_logs:
          type: kubernetes_logs

        # Kube Controller Manager
        # kube_controller_manager:
        #   type: prometheus_scrape
        #   endpoints: ["https://127.0.0.1:10257/metrics"]
        #   auth:
        #     strategy: "bearer"
        #     token: "eyJhbGciOiJSUzI1NiIsImtpZCI6InVkdmd5bzRpSGMyQzBacjRUX0l6S1l6Nm9XZ3RWYzFad3Nhc2g5aUJOVGMifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzQ2NjI5MDQ2LCJpYXQiOjE3NDY2MjU0NDYsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYTI0Y2QyZjItY2U4Mi00OWNhLTg1NWYtMWI4NGJkYmEwMDNkIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJ2ZWN0b3IiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoidmVjdG9yIiwidWlkIjoiMWI0Y2UwZjktODIxNS00YzRjLTk1MjMtNGY2OGM1YzRlYmI0In19LCJuYmYiOjE3NDY2MjU0NDYsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDp2ZWN0b3I6dmVjdG9yIn0.KgBuV5bHQYsqM0iJmEAY2uP-cbKgiSJ18LBvr9b0Fmkv97UWyMMct4LmFxWwY0q9RnyxsCJ-jS_risTVn6z-XZoaZ_KZMmowDlQliI7Tzh2LxWt-VSTAl526Cb4xVpSV4D_S1nVKOJrpwqpBt6wjKsXs9SKrmMzd_WSjEXGAnuEuPz1FMJIh7ch5qLf1r53Ks7KhlqUVJStRyAnQC3XJ5MncmCTF-q04lup3aqrxW9IG8Hqsp0bsOh6ukEqaVvhtPU0B0QOfZCT-nxZbp0RoTKxE8jcgroQh3Y8vvfMwWfq5XMqwVyAIq9Grxh0HTlU8TE7nDNNFlLmA7OKN95MHZA"   # "/var/run/secrets/kubernetes.io/serviceaccount/token"
        #   scrape_interval_secs: 15
        #   tls:
        #     verify_certificate: false
        #     verify_hostname: false
        # Kube Scheduler (добавлен)
        # kube_scheduler:
        #   type: prometheus_scrape
        #   endpoints: ["https://127.0.0.1:10259/metrics"]
        #   auth:
        #     strategy: "bearer"
        #     token: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        #   scrape_interval_secs: 15
        #   tls:
        #     verify_certificate: false
        #     verify_hostname: false
        # ETCD
        # kube_etcd:
        #   type: prometheus_scrape
        #   endpoints: ["http://127.0.0.1:2381/metrics"]
        #   scrape_interval_secs: 15
      # # Отправка метрик в Викторию
      # sinks:
        # victoria_metrics:
        #   type: prometheus_remote_write
        #   inputs: ["kube_etcd"] #["kube_controller_manager", "kube_scheduler", "kube_etcd"]
        #   endpoint: "http://vmsingle-victoria-metrics-vm.vm.svc.cluster.local:8429/api/v1/write"
        #   healthcheck:
        #     enabled: true
     
      sinks:
        loki_sink_messages:
          type: loki
          inputs:
            - file_messages
          endpoint: http://loki-gateway.loki.svc.cluster.local
          encoding:
            codec: json
          labels:
            logger: "vector-messages"
        loki_sink_kube:
          type: loki
          inputs:
            - kubernetes_logs
          endpoint: http://loki-gateway.loki.svc.cluster.local
          encoding:
            codec: json
          labels:
            logger: "vector-kube"
            # l_pod_name: "{{`{{kubernetes.pod_name}}`}}"

# Трансляция метрик на сервисе пода ( curl http://vector.vector.svc.cluster.local:9598/metrics )
        # etcd_prometheus_exporter:
        #   type: prometheus_exporter
        #   inputs: ["kube_etcd"]
        #   address: "0.0.0.0:9598"

        # cm_prometheus_exporter:
        #   type: prometheus_exporter
        #   inputs: ["kube_controller_manager"]
        #   address: "0.0.0.0:9597"

        # scheduler_prometheus_exporter:
        #   type: prometheus_exporter
        #   inputs: ["kube_scheduler"]
        #   address: "0.0.0.0:9599"
