apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vector-repo
  namespace: flux-system
spec:
  interval: 5m
  url: https://helm.vector.dev  # URL вашего Helm-репозитория
#  secretRef:  # Опционально, если требуется аутентификация
#    name: helm-repo-credentials