apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  -  ../../../base/cert-manager
  


patchesJson6902:
  - target:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: cert-manager
    patch: |-
      - op: replace
        path: /metadata/name
        value: certmanager2
