apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: kube-state-metrics
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-state-metrics  # Название чарта
      version: "5.31.1" # Версия чарта (опционально)
      sourceRef:
        kind: HelmRepository
        name: kube-state-metrics-repo
        namespace: flux-system
      interval: 1m