apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: grafana-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana-operator  # Название чарта
      version: "v5.17.0" # Версия чарта (опционально)
      sourceRef:
        kind: HelmRepository
        name: grafana-operator-repo
        namespace: flux-system
      interval: 1m
