apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 00-pre
  namespace: flux-system
spec:
  interval: 5m
  path: "../../clusters/test-cluster/00-PRE/"  # Путь к папке с PRE-ресурсами
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # healthChecks можно добавить для CRD (пример ниже)