apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 00-pre
  namespace: flux-system
spec:
  interval: 1m          # Проверяет состояние каждые 1 минут
  retryInterval: 1m     # Повторяет неудачные попытки каждую минуту
  timeout: 2m           # Прерывает операцию, если она длится дольше 2 минут
  path: "../../clusters/test-cluster/00-PRE/"  # Путь к папке с PRE-ресурсами
  prune: true  # Удаляет ресурсы, удалённые из Git
  force: true  # Принудительно перезаписывает изменения
  sourceRef:
    kind: GitRepository
    name: flux-system
  # healthChecks:   # можно добавить... 