apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 01-payload
  namespace: flux-system
spec:
  interval: 5m
  path: "../../clusters/test-cluster/01-PAYLOAD/"  # Путь к основному приложению
  prune: true
  dependsOn:  # Ждем завершения 00-PRE
    - name: 00-pre
  sourceRef:
    kind: GitRepository
    name: flux-system