apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 02-post
  namespace: flux-system
spec:
  interval: 5m
  path: "../../clusters/test-cluster/02-POST/"  # Путь к POST-ресурсам
  prune: true
  force: true
  dependsOn:  # Ждем завершения 01-PAYLOAD
    - name: 01-payload
  sourceRef:
    kind: GitRepository
    name: flux-system