apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - Kustomization.yaml
  - my-flux-instance.yaml
  - ../../base/headlamp
  - ../../base/ingress-nginx
  - ../../base/local-path-provisioner
  # - ../../base/cert-manager
  - base/cert-manager
  - ../../base/grafana/grafana-operator
  - ../../base/grafana/loki
  - ../../base/kubernetes-metrics-server
  - ../../base/authentik
  - ../../base/victoria-metrics
  - ../../base/vector
  # - ../../../base/kube-state-metrics


patches:
  - path: base/ingress-nginx/patches.yaml
  - path: base/headlamp/patches.yaml
  # - path: base/cert-manager/patches.yaml

