apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - Kustomization.yaml
  - my-flux-instance.yaml
  - ../../base/headlamp
  - ../../base/ingress-nginx
  - ../../base/local-path-provisioner
  # - ../../base/cert-manager
  - base/cert-manager # Демонстрация альтернативного разворачивания приложения, которое не совпадает с base совсем (в данном случае namespace другой)
  - base/vector # Дополнительный ингресс для заливки логов в Локи извне
  - ../../base/grafana/grafana-operator
  - ../../base/grafana/loki
  - ../../base/kubernetes-metrics-server
  - ../../base/authentik
  - ../../base/victoria-metrics
  - ../../base/vector
  # - ../../../base/kube-state-metrics  # Если ставить полный стек Виктории, то там должен быть встроенный, а потому этот выключил


patches:
  - path: base/ingress-nginx/patches.yaml
  - path: base/headlamp/patches.yaml
  # - path: base/cert-manager/patches.yaml

