apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: headlamp  # Название чарта
      version: "0.29.1" # Версия чарта (опционально)
      sourceRef:
        kind: HelmRepository
        name: headlamp-repo
        namespace: flux-system
      interval: 1m
#  values:  # Кастомные values для чарта