apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: external-grafana  # Имя должно совпадать с instanceSelector в GrafanaFolder
  namespace: grafana-op2  # Должен совпадать с namespace GrafanaFolder
  labels:
    dashboards: "external-grafana"  # Метка для matchExpressions
spec:
  config:
    auth:
      disable_login_form: false
    auth.anonymous:
      enabled: false  # Для безопасности лучше отключить анонимный доступ
    log:
      mode: "console"
      level: "warn"
    security:
      admin_user: "admin"
      admin_password: "strongpassword"  # Замените на надежный пароль
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
  instanceSelector:  # Опционально, если нужно явно указать селектор
    matchLabels:
      dashboards: "external-grafana"
  ingress:
    enabled: true
    targetPort: 3000
    path: /
    hostname: grafana.example.com  # Укажите ваш домен
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 3000
        targetPort: 3000