apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: external-grafana
  namespace: grafana-operator
  labels:
    dashboards: "external-grafana"  
spec:
  config:
    auth:
      disable_login_form: "false"
    auth.anonymous:
      enabled: "false"
    security:
      admin_user: "admin"
      admin_password: "111"
  # client:
  #   preferService: true