apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-provisioner
spec:
  interval: 1m
  driftDetection:
    mode: enabled # Следит за изменениями и возвращает к состоянию как в Git  
  chart:
    spec:
      chart: local-path-provisioner  # Название чарта
      version: "0.0.23" # Версия чарта (опционально)
      sourceRef:
        kind: HelmRepository
        name: local-path-provisioner-repo
        namespace: flux-system
      interval: 1m
  # upgrade:
  #   remediation:
  #     remediateLastFailure: true
  #     retries: 5
    # force: true  # Опционально, если нужно пересоздавать Pod'ы

  # install:
  #   remediation:
  #     retries: 5
  values:
    storageClass:
      defaultClass: true
      reclaimPolicy: Delete