apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-provisioner
spec:
  interval: 5m
  chart:
    spec:
      chart: local-path-provisioner  # Название чарта
      version: "0.0.23" # Версия чарта (опционально)
      sourceRef:
        kind: HelmRepository
        name: local-path-provisioner-repo
        namespace: flux-system
      interval: 1m
  values:
    storageClass:
      defaultClass: true
      reclaimPolicy: Delete