apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager  # Название чарта
      version: "v1.17.1" # Версия чарта (опционально)
      sourceRef:
        kind: HelmRepository
        name: cert-manager-repo
        namespace: flux-system
      interval: 1m
  values:
    installCRDs: true