---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx  # Название чарта
      version: "4.12.0" # Версия чарта (опционально)
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-repo
        namespace: flux-system
      interval: 1m
  values:  # Кастомные values для чарта
    controller:
      kind: DaemonSet
      # tolerations:
      #   - key: "node-role.kubernetes.io/ingress"
      #     operator: "Exists"
      #     effect: "NoSchedule"
      metrics:
        enabled: true
      service:
        #type: LoadBalancer
        type: NodePort  
      hostNetwork: true
      ingressClassResource:
        default: true
      allowSnippetAnnotations: true
      enableAnnotationValidations: false
      config:
        annotations-risk-level: "Critical"
        use-forwarded-headers: "true"
      # nodeSelector:
      #   node-role.kubernetes.io/ingress: ""
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 5m
  chart:
    spec:
      chart: headlamp  # Название чарта
      version: "0.29.1" # Версия чарта (опционально)
      sourceRef:
        kind: HelmRepository
        name: headlamp-repo
        namespace: flux-system
      interval: 1m
  values:  # Кастомные values для чарта
    config:
      baseURL: ""
      oidc:
        clientID: kube-oidc
        clientSecret: Vdqzap389jEkB6g7o6KfrBy82aabPZt2siFglLQA32pmNR0K0lmADaL0jSNxxAsa5qxjACIBFBU0JEI3apSax7aXRNAnaiASxeEcXDgydcHnB210bbPSNFD1JwE8uUlx
        issuerURL: https://authentik.xal.su/application/o/kube-oidc/
        scopes: "openid,profile,email"
        secret:
          create: true
          name: headlamp-oidc
      pluginsDir: /headlamp/plugins