apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/headlamp
  - ../../base/ingress-nginx
  - ../../base/local-path-provisioner
  - ../../base/cert-manager

  # - ../../base/flux-monitoring
patches:
  - path: bundle-patches.yaml

